package io.satori.quiz.mapper;

import io.satori.quiz.dto.QuestionCreationRequestDto;
import io.satori.quiz.dto.QuestionDto;
import io.satori.quiz.model.Question;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.factory.Mappers;

import java.util.List;

@Mapper(componentModel = "spring") // componentModel = "spring" allows Spring to manage it as a bean
public interface QuestionMapper {

    QuestionMapper INSTANCE = Mappers.getMapper(QuestionMapper.class);

    // Maps Question entity to QuestionDto (for client display, e.g., in a quiz)
    QuestionDto questionToQuestionDto(Question question);

    List<QuestionDto> questionsToQuestionDtos(List<Question> questions);

    // Maps QuestionCreationRequestDto to Question entity (for saving a new question)
    @Mapping(target = "id", ignore = true) // id is auto-generated by the database
    Question questionCreationRequestDtoToQuestion(QuestionCreationRequestDto dto);

    // If you need to map a full Question entity (including rightAnswer) to a DTO
    // for other purposes (e.g., an admin view of all question details),
    // you could create another DTO (e.g., AdminQuestionDto) and a mapping for it.
    // For now, QuestionDto is designed for client-side quiz taking.
}